name: chidboilerplate
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Routing
  go_router: ^13.0.1

  # Bloc State Management
  flutter_bloc: ^8.1.3

  # Icons
  cupertino_icons: ^1.0.2

  # Comparing Objects
  equatable: ^2.0.3

  # Http Request Call
  http: ^0.13.4

  # Opening URL
  url_launcher: ^6.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
